### ISSUE TITLE
The Guardian

### ISSUE THREAD

**Issue by lenymo** [coreybruyere/bem-real-world-examples#2]
[The Guardian](https://www.theguardian.com/) uses BEM!

I came across your listing while looking for some real-world applications of BEM which I'm trying to implement on a personal project. I see it hasn't been updated in a bit but this would add to it nicely.

If I knew how to make a pull request I would do that but this is the next best thing.

**Comment by coreybruyere** [comment]
Thanks @lenymo - I need to update this repo. I've come across more and more sites using BEM lately. I'll make sure to add your find 👍
